title: Cristina Marin # your name (or website title) here
logo: "/images/CM.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Curious and detail focused person with a passion for the exploration of human and artificial intelligence
  <br><br>
  I am looking to work in data analysis
  <br><br>
  <a href="https://www.linkedin.com/in/cristina-marin-sheffield/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
